<?php
/**
 * Created by PhpStorm.
 * User: daniel
 * Date: 12/11/18
 * Time: 10:08 PM
 */

namespace TUSIMO\Http\Resources;
use Illuminate\Http\Resources\Json\ResourceCollection;

class EventsCollection extends ResourceCollection
{
    public function toArray($request)
    {
        return parent::toArray($request); // TODO: Change the autogenerated stub
    }
}