<?php

namespace TUSIMO\Http\Resources;

use Illuminate\Http\Resources\Json\ResourceCollection;

class LugaresCollection extends ResourceCollection
{
    public function toArray($request)
    {
        return parent::toArray($request); // TODO: Change the autogenerated stub
    }
}