<?php
/**
 * Created by PhpStorm.
 * User: daniel
 * Date: 12/9/18
 * Time: 11:30 PM
 */

namespace TUSIMO\Http\Resources;

use Illuminate\Http\Resources\Json\ResourceCollection;

class UsersCollection extends ResourceCollection
{
    public function toArray($request)
    {
        return parent::toArray($request); // TODO: Change the autogenerated stub
    }
}